baseurl = "/"
languageCode = "en-us"
title = "Seely Street Bed and Breakfast"

#sectionPagesMenu = "main"

[[menu.main]]
    name = "Welcome"
    url = "/"
    pre ="home"
    weight = 1
[[menu.main]]
    name = "Rooms"
    url = "/rooms/"
    weight = 2
[[menu.main]]
    name = "Contact Us"
    url = "/contact/"
    weight = 3
[[menu.main]]
    name = "Facilities"
    url = "/facilities/"
    weight = 4
[[menu.main]]
    name = "MTB/Hiking"
    url = "/biking/"
    weight = 5
[[menu.main]]
    name = "History"
    url = "/history/"
    weight = 6
[[menu.main]]
    name = "T&C's"
    url = "/conditions/"
    weight = 7

[params]
    description = "Seely Street Bed and Breakfast"
    footer = "&copy; [Seely Street Bed & Breakfast](https://seelystreet.com) 2022"

[markup]
defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[build]
  command = "hugo"
    publish = "public"

    [build.environment]
      HUGO_VERSION = "0.91.2"

